<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Introduction to Web Services and APIs

_Author: Dave Yerrington (SF)_

### Learning Objectives
*After this lesson, you will be able to:*
- Identify relevant Hyper Text Transfer Protocal (HTTP) Verbs & their uses.
- Describe Application Programming Interfaces (APIs) and know how to make calls and consume API data.
- Access public APIs and get information back.
- Read and write data in JavaScript Object Notation (JSON) format.
- Use the `requests` library.

keywords: API, calls, JSON

<a id='what-is-api'></a>
## What is an API?

---

A good interface allows you to interact with something in a standardized way without worrying about implementation details. For example:

- **A door handle.** We don't care how a door works. All that we expect is that pushing or pulling the handle will open the door. In fact, the way the door opens (theoretically) could be entirely different each time we use the door. 

- **File->Print.** We don't care how the computer prints the document. All that we expect is that using the Print option in the File menu will print the document. In fact, the way the computer prints it could change every time the program is updated. 

An **API (Application Programming Interface)** is a *programming interface* to a *software application*.

- **Matplotlib `plot()`**: We don't care how the `plot()` function works. All that we expect is that calling this function (with appropriate parameters) will plot the data and return a graphic. In fact, how the function works can completely change from version to version. 

The functions that you call and the parameters you call them with make up the interface to a programming library.

Some examples of tasks that APIs can assist with are:

- Connecting to databases
- Turning LED lights on and off
- Making applications that run on Windows, OSX, and Linux
- Posting content to Twitter, Facebook, Yelp, or LinkedIn
- Accessing currency or stock prices

#### Web APIs

A Web API is a list of **function calls** that are made to remote servers. The function call is sent by encoding it as a URL (technically, as an HTTP request -- we'll discuss these later!). The function call typically returns a string of text (e.g. JSON).

### Why did APIs become popular?

APIs became popular for many reasons:

- Easy to use programmers
- Prevent website scraping
- Allow a website's brand to be incorporated into other websites 

Nearly every website uses **internal APIs** for shuttling dynamic data between the browser and the website. Some websites also expose **external APIs**, e.g. for querying databases.

### Web Scraping

- Using code to obtain data from a website without going through an external API is called **web scraping**.
- Many websites provide rules for web scraping in a `robots.txt` file.
- You may be blocked from visiting a website if you violate those rules or otherwise abuse your access, e.g. by downloading an excessive amount of data.

<a id='famous'></a>
<a id='facebook'></a>

### Famous APIs:  Facebook Graph API

Facebook provides an API for interacting with their service in the following ways:

- View your posts
- View websites, people, posts, pages that you've liked
- View activity on apps from you and your friends
  - Movies watched
  - Music listened
  - Games played
- View places traveled / check-ins

#### Potential Project Ideas:

|   |   |   |   |
|---|---|---|---|
| Determining Latent Characteristics | Friends Activity | Political Classification | Text Mining |
| Friend Classifier | Trending Topics | Recommenders | Feature Importances |
| Taste Profiling | Hipster Detector | Sub-group Identification | Checkin-Prediction |
| Relationship Forcasting | Relationship Classification | Sentiment Analysis | Popularity Projection |
| Personal Analytics | Friend Similarity Prediction | N-Gram Analysis | Topic Modeling |

<a id='yelp'></a>
### Famous APIs:  Yelp API

Yelp provides a way for developers to access:

- Reviews
 - Services
 - Restaraunts / Bars / Cafes
 - Businesses
- Business meta-data

#### Potential Project Ideas

|   |   |   |   |
|---|---|---|---|
| Topic Modeling | Text Mining | Sentiment Analysis | Funny / Cool / Interesting Classification | 
| Music Genre Classification | Parking Index Classification | Characteristics Profiling | Hipster Index |
| Ideal Activities | Friend Recommender | Venue Recommender | Sports Bar Classifcation |
| Where is the best [whatever] in [neighborhood] | | |

<a id='echonest'></a>
### Famous APIs:  Echonest

Echonest consolidates access to many entertainment service APIs in one place.  It has a huge list of features and connected services including:

- Spotify
- Pandora
- Rdio
- Gracenote
- SoundHound
- Shazam

Some Echonest features include:

- Music waveform identification (like Shazam, Soundhound music ID)
- Playlist recommendations
- Detailed artist, album, and track lookup
 - Bio / Origins / Contemporaries / Noteworthy Accomplishments
 - Official twitter / website / social media links
 - BPM / Mood / Popularity / Genre(s) 
 - Images / Videos / Media
- Detailed movie, actor, product lookup
- Concert Schedules and ticket metadata

<a name="api-calls"></a>
## Making API calls

---

An API call is an HTTP request to a server. Whereas the standard HTTP requests that your web browser makes return HTML and other assets (e.g. images) for display in a browser, an API call returns data, typically as text in JSON or XML format.

[Representational state transfer (REST)](https://spring.io/understanding/REST) is the most common architecture style for passing information to and from these API endpoints.

### API Tokens

Many APIs are free to access. You first need to register as a developer and obtain an authorization key. In most cases, this is also accompanied by a temporary token that needs to be renewed after some time. This is a way to prevent abuse on the server's resources. 

- For example, the Twitter API requires a token that is used to track how many requests each user makes. Each user can retrieve a limited number of tweets, unless they pay for premium services.

<a id='http'></a>
## HTTP

---

**HTTP (HyperText Transfer Protocol)** is a protocol - a system of rules - that determines how web pages (see:'hypertext') get sent from one place to another. Among other things, it defines the format of the messages passed between HTTP clients and HTTP servers.

Since the web is a service, it works through a combination of **clients** (that _make_ requests) and **servers** (that _receive_ requests).


### The HTTP client

**HTTP clients** make or generate **HTTP requests**. Some types of clients are:

* Browsers - Chrome, Firefox and Safari.
* Command Line programs - [curl](http://curl.haxx.se/docs/) and [wget](http://www.gnu.org/software/wget/manual/wget.html).
* Application code -  Python Requsts, Scrapy, Mechanize

HTTP clients respond to HTTP responses from a **web server**/**HTTP server**. A web server is just a computer that listens for and responds to HTTP requests.

<a id='web-app'></a>
## Web applications

---

Web applications are programs that run on a web server. They process the HTTP requests that the server receives and generate HTTP responses.

![HTTP Request and Response](./assets/request-response.png)

1. A client sends an HTTP request to an HTTP server running on a remote machine.  
  * The _hostname_, given in the URL, indicates which server will receive the request.  
2. The HTTP server processes the HTTP request. This may entail passing the request to some web application, which creates an HTTP response. 
3. The HTTP server sends the HTTP response gets sent back to the client.
4. The client processes the response.

A URL specifies where a resource can be found on the web.

![URL](./assets/http1-url-structure.png)

<a name="demo-http"></a>
## Demo: HTTP

---

- Let's explore HTTP resources.
- In Chrome, open up Chrome Inspector (*command + option + 'i', or ctrl + click and select 'inspect element'*).

![HTTP Request and Response](./assets/http_request_response.jpeg "HTTP Request and Response")

* Select the Network tab.
* Go to the URL https://generalassemb.ly/

You should be able to see a few HTTP requests and responses in the Network tab.

- Most of this information comes from the HTTP Request and Response.
- Some HTTP requests are for CSS, JavaScript and images that are referenced by the HTML.
- Select generalassemb.ly in the Path column on the far left.
- Select the Headers tab. Headers are meta-data properties of an HTTP request or response, separate from the body of the message.

The first word in the request line, _GET_, is the **HTTP method**.

<a id='request-methods'></a>
### HTTP Request methods:

* **`GET`** => Retrieve a resource.  
* **`POST`** => Create a resource.  
* **`PATCH`** (_or **`PUT`**, but **`PATCH`** is recommended_) => Update an existing resource.  
* **`DELETE`** => Delete a resource.  
* **`HEAD`** => Retrieve the headers for a resource.

Of these, **`GET`** and **`POST`** are the most widely used.

<a id='ind-http'></a>

**Exercise**

- Go to your favorite website(s) (safe for work) with the Chrome network inspection tool turned on (cmd-opt-i). Find the initial request. Look at the request and response headers and the content of the response. Explore the other requests, trying to identify what initiated them and what they contain.

<a id='request-structure'></a>
### HTTP Request structure:

```
[http request method] [URL] [http version]  
[list of headers]

[request body]
```

*Notice that the request header is separated from the request body by a new line.*

**HTTP Request Method Example: (No Body)**

    GET http://vermonster.com HTTP/1.1  
    Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8  
    Accept-Encoding:gzip,deflate,sdch
    Accept-Language:en-US,en;q=0.8  
    Connection:keep-alive  
    Host:vermonster.com  
    User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5)  
    AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1659.2 Safari/537.36  

<a id='http-response'></a>
## HTTP Response

---

![HTTP Response](./assets/http_response.jpeg "HTTP Response")

When a client sends a request, the server sends back a response; the standard format for this response is:

```
[http version] [status] [reason]  
[list of headers]

[response body] # typically HTML, JSON, ..  
```

<a id='response-types'></a>
### Response types overview

> Check these out when you have time -- at least be aware that there is an expected pattern to these codes:

**[Status codes](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes)** have standard meanings; here are a few.

|Code|Reason|
|:---|:-----|
|200| OK
|301| Moved Permanently
|302| Moved Temporarily
|307| Temporary Redirect
|400| Bad Request
|403| Forbidden
|404| Not Found
|500| Internal Server Error

### Recap: What is a dictionary in Python?

# JSON

```javascript
[
	{
		"source": "Twitter for iPhone",
		"text": "If the E.U. wants to further increase their already massive tariffs and barriers on U.S. companies doing business there, we will simply apply a Tax on their Cars which freely pour into the U.S. They make it impossible for our cars (and more) to sell there. Big trade imbalance!",
		"created_at": "Sat Mar 03 17:53:50 +0000 2018",
		"is_retweet": false,
		"id_str": "969994273121820672"
	},
	{
		"source": "Twitter for iPhone",
		"text": "The United States has an $800 Billion Dollar Yearly Trade Deficit because of our “very stupid” trade deals and policies. Our jobs and wealth are being given to other countries that have taken advantage of us for years. They laugh at what fools our leaders have been. No more!",
		"created_at": "Sat Mar 03 17:43:26 +0000 2018",
		"is_retweet": false,
		"id_str": "969991653393039361"
	}
]
```

<a name="json"></a>
## JSON

---

JSON is short for _JavaScript Object Notation_. It is called JSON because a JSON string is valid JavaScript code.

**Aside:** Javascript is a programming language, like Python. It is the standard language for web programming. It is totally different from the programming language Java.

**JSON is built on two structures:**

|Description | Javascript name | Python counterpart |
|----|-----|----|
|Collection of key/value pairs | object | dict |
|Ordered collection of values | array | list |

<a name="ind-practice"></a>
**Exercise.**

- Go to https://codebeautify.org/jsonviewer
- Paste the JSON provided below into the JSON Input box.
- Click "Beautify."

* Identify the structure of the JSON:
    - How many arrays are there?
    - How many objects are there?
    - What are the attributes of an object?

```javascript
[{"source":"Twitter for iPhone","text":"If the E.U. wants to further increase their already massive tariffs and barriers on U.S. companies doing business there, we will simply apply a Tax on their Cars which freely pour into the U.S. They make it impossible for our cars (and more) to sell there. Big trade imbalance!","created_at":"Sat Mar 03 17:53:50 +0000 2018","retweet_count":22641,"favorite_count":87398,"is_retweet":false,"id_str":"969994273121820672"},{"source":"Twitter for iPhone","text":"The United States has an $800 Billion Dollar Yearly Trade Deficit because of our “very stupid” trade deals and policies. Our jobs and wealth are being given to other countries that have taken advantage of us for years. They laugh at what fools our leaders have been. No more!","created_at":"Sat Mar 03 17:43:26 +0000 2018","retweet_count":22563,"favorite_count":90540,"is_retweet":false,"id_str":"969991653393039361"}]
```

<a name="guided-practice"></a>
## Guided practice: Pulling data from APIs

<a id='ex1-star-wars'></a>
### Example 1: Star Wars  (Go to SWAPI Exercise.ipynb)

**Let's try for example to retrieve the data about the "Obi-Wan Kenobi".**

Referencing the [SWAPI Documentation](http://swapi.co/documentation), lets create a query to search for characters with "obi" in their name.

```javascript
{
    "count": 1,   
    "next": null,   
    "previous": null,   
    "results": [  
        {  
            "name": "Obi-Wan Kenobi",   
            "height": "182",   
            "mass": "77",   
            "hair_color": "auburn, white",   
            "skin_color": "fair",   
            "eye_color": "blue-gray",   
            "birth_year": "57BBY",   
            "gender": "male",   
            "homeworld": "http://swapi.co/api/planets/20/",   
            "films": [    
                "http://swapi.co/api/films/2/",   
                "http://swapi.co/api/films/5/",   
                "http://swapi.co/api/films/4/",   
                "http://swapi.co/api/films/6/",   
                "http://swapi.co/api/films/3/",   
                "http://swapi.co/api/films/1/"  
            ],   
            "species": ["http://swapi.co/api/species/1/"],     
            "vehicles": ["http://swapi.co/api/vehicles/38/"],   
            "starships": [  
                "http://swapi.co/api/starships/48/",     
                "http://swapi.co/api/starships/59/",   
                "http://swapi.co/api/starships/64/",   
                "http://swapi.co/api/starships/65/",   
                "http://swapi.co/api/starships/74/"  
            ],   
            "created": "2014-12-10T16:16:29.192000Z",     
            "edited": "2014-12-20T21:17:50.325000Z",     
            "url": "http://swapi.co/api/people/10/"    
        }  
    ]  
}  
```

###  What Just Happened?

We requested a url, which responded with JSON.

SWAPI has a GUI-based response as well which is the default.

https://swapi.co/api/people/?search=obi

Also a Wookie-flavored one:

https://swapi.co/api/people/?format=wookiee&search=obi

<a id='submit'></a>
**Exercise**.

- Retrieve three additional responses from SWAPI.

- **Bonus:** Query SWAPI from the command line using the app `curl`. Try typing:

    `curl http https://swapi.co/api/people/1/`

```javascript   
{
	"name": "Luke Skywalker",
	"height": "172",
	"mass": "77",
	"hair_color": "blond",
	"skin_color": "fair",
	"eye_color": "blue",
	"birth_year": "19BBY",
	"gender": "male",
	"homeworld": "https://swapi.co/api/planets/1/",
	"films": [
		"https://swapi.co/api/films/2/",
		"https://swapi.co/api/films/6/",
		"https://swapi.co/api/films/3/",
		"https://swapi.co/api/films/1/",
		"https://swapi.co/api/films/7/"
	],
	"species": [
		"https://swapi.co/api/species/1/"
	],
	"vehicles": [
		"https://swapi.co/api/vehicles/14/",
		"https://swapi.co/api/vehicles/30/"
	],
	"starships": [
		"https://swapi.co/api/starships/12/",
		"https://swapi.co/api/starships/22/"
	],
	"created": "2014-12-09T13:50:51.644000Z",
	"edited": "2014-12-20T21:17:56.891000Z",
	"url": "https://swapi.co/api/people/1/"
}
```

### Using the requests library

In [1]:
# Request example for the SWAPI example
import pandas as pd
import requests

response = requests.get('http://swapi.co/api/people/10')
print (response)

<Response [200]>


In [2]:
# Convert response to JSON
response.json()

{'birth_year': '57BBY',
 'created': '2014-12-10T16:16:29.192000Z',
 'edited': '2014-12-20T21:17:50.325000Z',
 'eye_color': 'blue-gray',
 'films': ['https://swapi.co/api/films/2/',
  'https://swapi.co/api/films/5/',
  'https://swapi.co/api/films/4/',
  'https://swapi.co/api/films/6/',
  'https://swapi.co/api/films/3/',
  'https://swapi.co/api/films/1/'],
 'gender': 'male',
 'hair_color': 'auburn, white',
 'height': '182',
 'homeworld': 'https://swapi.co/api/planets/20/',
 'mass': '77',
 'name': 'Obi-Wan Kenobi',
 'skin_color': 'fair',
 'species': ['https://swapi.co/api/species/1/'],
 'starships': ['https://swapi.co/api/starships/48/',
  'https://swapi.co/api/starships/59/',
  'https://swapi.co/api/starships/64/',
  'https://swapi.co/api/starships/65/',
  'https://swapi.co/api/starships/74/'],
 'url': 'https://swapi.co/api/people/10/',
 'vehicles': ['https://swapi.co/api/vehicles/38/']}

In [4]:
# Load JSON response into a pandas DataFrame
pd.DataFrame([response.json()])

birth_year                      created                       edited  \
0      57BBY  2014-12-10T16:16:29.192000Z  2014-12-20T21:17:50.325000Z   

   eye_color                                              films gender  \
0  blue-gray  [https://swapi.co/api/films/2/, https://swapi....   male   

      hair_color height                         homeworld mass  \
0  auburn, white    182  https://swapi.co/api/planets/20/   77   

             name skin_color                            species  \
0  Obi-Wan Kenobi       fair  [https://swapi.co/api/species/1/]   

                                           starships  \
0  [https://swapi.co/api/starships/48/, https://s...   

                               url                             vehicles  
0  https://swapi.co/api/people/10/  [https://swapi.co/api/vehicles/38/]

<a id='ex2-geocode'></a>
### Example 2: Google Geocode API

Google offers a freely accessible API to query their GEO databases.  One of the many features Google Maps API provides is a way to get longitude and latitude coordinates from addresses.

**Try pasting the following line in your browser:**

    https://maps.googleapis.com/maps/api/geocode/json?address=225+Bush+St+San+Francisco+CA

In [6]:
# Request the resource from google maps
response = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address=225+Bush+St+San+Francisco+CA')
response.json()

{'results': [{'address_components': [{'long_name': '225',
     'short_name': '225',
     'types': ['street_number']},
    {'long_name': 'Bush Street', 'short_name': 'Bush St', 'types': ['route']},
    {'long_name': 'Financial District',
     'short_name': 'Financial District',
     'types': ['neighborhood', 'political']},
    {'long_name': 'San Francisco',
     'short_name': 'SF',
     'types': ['locality', 'political']},
    {'long_name': 'San Francisco County',
     'short_name': 'San Francisco County',
     'types': ['administrative_area_level_2', 'political']},
    {'long_name': 'California',
     'short_name': 'CA',
     'types': ['administrative_area_level_1', 'political']},
    {'long_name': 'United States',
     'short_name': 'US',
     'types': ['country', 'political']},
    {'long_name': '94104', 'short_name': '94104', 'types': ['postal_code']}],
   'formatted_address': '225 Bush St, San Francisco, CA 94104, USA',
   'geometry': {'location': {'lat': 37.7908343, 'lng': -122.40

```javascript
{'results': [{'address_components': [{'long_name': '225', 'short_name': '225', 'types': ['street_number']}, {'long_name': 'Bush Street', 'short_name': 'Bush St', 'types': ['route']}, {'long_name': 'Financial District', 'short_name': 'Financial District', 'types': ['neighborhood', 'political']}, {'long_name': 'San Francisco', 'short_name': 'SF', 'types': ['locality', 'political']}, {'long_name': 'San Francisco County', 'short_name': 'San Francisco County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}, {'long_name': '94104', 'short_name': '94104', 'types': ['postal_code']}], 'formatted_address': '225 Bush St, San Francisco, CA 94104, USA', 'geometry': {'location': {'lat': 37.7908343, 'lng': -122.4015725}, 'location_type': 'ROOFTOP', 'viewport': {'northeast': {'lat': 37.7921832802915, 'lng': -122.4002235197085}, 'southwest': {'lat': 37.7894853197085, 'lng': -122.4029214802915}}}, 'place_id': 'ChIJZXDI4YmAhYAReSK9_qXi2Oo', 'types': ['street_address']}], 'status': 'OK'}
```

**Exercise**

- Extract the latitude and longitude from this response.

*Tips:*

- Work incrementally, digging into the JSON one level at a time.
- If you are having trouble reading the JSON, you might copy and paste the response into https://codebeautify.org/jsonviewer to "beautify" it. You may need to convert single quotes to double quotes first, e.g. using Python's `.replace` string method.

In [19]:
response.json()['results'][0]['geometry']['location']

{'lat': 37.7908343, 'lng': -122.4015725}

<a name="ind-practice2"></a>
## Practice: Python APIs

---

**Form pairs and do the following:** 

Go to http://www.pythonforbeginners.com/api/list-of-python-apis or https://github.com/realpython/list-of-python-api-wrappers
  
- Find a partner
- Choose an API
- Install the relevant Python module, if available.
- Try to extract data from the API
- Discuss: How could you leverage that api? How could you use the data?

<a id='closing-questions'></a>
## Closing questions

- What aspect of this material is hardest to understand?
- How would you explain APIs to someone who didn't know anything about them?
- Any new ideas for capstone data?

# Questions?

## Exercise Time!!

# [Exit Tickets](https://goo.gl/forms/bJuNA1LpN2goAYmT2)